# _config.yml
#remote_theme: mimneko/Kiss-Jekyll-Lite

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      
title: "みむねこのーと"   # サイトの名前
launch_date: "2023-12-11"     # 開設日
mimnekonote_url: "https://mimneko.github.io/note"
